resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: mywebapp

commonAnnotations:
  app: mykustom-annotations

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
  - name: bos-herken-tbg-rfh2-xml
    files:
      - identification.json
    options:
      labels:
        app: mywebapp
